data<-read.table("power.txt", header=TRUE, sep=";")
data2<-subset(data,data$Date=="1/2/2007"|data$Date=="2/2/2007")
hist(as.numeric(data2$Global_active_power),main="Global active power", xlab="Global Active Power, (kilowatts)", col="red")
dev.copy(png, file = "plot1.png", width=480, height=480)
dev.off()