data<-read.table("power.txt", header=TRUE, sep=";")
data2<-subset(data,data$Date=="1/2/2007"|data$Date=="2/2/2007")
t<-strptime(paste(data2$Date, data2$Time), format="%d/%m/%Y %H:%M:%S")
plot(x=t, y=data2$Global_active_power, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png, file = "plot2.png", width=480, height=480)
dev.off()
